version: '3'
services:
  web:
    container_name: nginx3
    ports:
      - "8081:80"
    volumes:
      - "/home/gresshel/workspace/docker/10-docker-compose/html:/usr/share/nginx/html"
    image: nginx

