version: '3'
services:
  web1:
    container_name: apache1
    ports:
      - "8081:80"
    image: httpd
    networks:
      - net-test
  web2:
    container_name: apache2
    ports:
      - "8082:80"
    image: httpd
    networks:
      - net-test
networks:
  net-test:

